hector_exploration_planner:
  smoothing_enabled:              false
  smoothed_points_per_unit:       2
  smoothed_points_throttle:       3
  smoothed_use_end_conditions:    false
  smoothed_use_middle_conditions: false