k_trans: 2.0
k_rot: 2.0

tolerance_trans: 0.1
tolerance_rot: 0.2
tolerance_timeout: 0.5

holonomic: false

samples: 10

max_vel_lin: 0.9
max_vel_th: 0.9

min_vel_lin: 0.1
min_vel_th: 0.0
min_in_place_vel_th: 0.0
in_place_trans_vel: 0.0

trans_stopped_velocity: 1e-4
rot_stopped_velocity: 1e-4

robot_base_frame: base_link
global_frame: odom